project:
  type: website
  output-dir: docs

website:
  google-analytics: G-072EP0BQB1
  favicon: images/headshot.jpg
  title: "INESSA DE ANGELIS"
  site-url: "https://inessadeangelis.ca"
  navbar:
    background: secondary
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
    right: 
    - icon: envelope-at
      href: "mailto:Inessa.DeAngelis@mail.utoronto.ca"
    - icon: github
      href: https://github.com/InessaDeAngelis
    - icon: linkedin
      href: https://www.linkedin.com/in/inessa-de-angelis/
    - icon: twitter
      href: https://twitter.com/inessadeangelis
      
  page-footer:
    background: light
    center: "© 2024 Inessa De Angelis"

format:
  html:
    theme: 
      - minty
      - minty.scss
    mainfont: Lato
    css: styles.css
    toc: true

editor: visual
