project:
  type: website
  output-dir: docs

website:
  google-analytics: G-072EP0BQB1
  favicon: images/headshot.jpg
  title: "INESSA DE ANGELIS"
  site-url: "https://inessadeangelis.ca"
  navbar:
    background: secondary
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: media.qmd
        text: Media
    right: 
    - icon: envelope-at
      href: "mailto:Inessa.DeAngelis@mail.utoronto.ca"
    - icon: github
      href: "https://github.com/InessaDeAngelis"
    - icon: linkedin
      href: "https://www.linkedin.com/in/inessa-de-angelis/"
    - text: "{{< fa brands bluesky >}}"
      href: "https://bsky.app/profile/inessadeangelis.bsky.social"
  
  page-footer:
    background: light
    center: "© 2025 Inessa De Angelis"

format:
  html:
    theme: 
      - minty
      - minty.scss
    mainfont: Lato
    css: styles.css
    toc: false

editor: visual
