---
title: "Media"
---

I am available for media commentary on Canadian politics, political communication, the political uses of social media and AI, online harassment, and violence against women in politics. 

For media inquiries, please [email me](mailto:Inessa.DeAngelis@mail.utoronto.ca).

#### Interviews

::: {style="text-align: left"}
- [‘Thank God we don’t have the media’: Ford holds another funding announcement without inviting reporters](https://www.thetrillium.ca/news/politics/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12740621). *The Trillium*, September 3, 2026.
  - Republished in: [*Aurora Today*](https://www.auroratoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12744527), [*Barrie Today*](https://www.barrietoday.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-announcement-without-reporters-12747041), [*Bay Today*](https://www.baytoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12746601), [*Bradford Today*](https://www.bradfordtoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12746381), [*Burlington Today*](https://www.burlingtontoday.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12744989), [*Dundas Today*](https://www.dundastoday.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12743867), [*Elliot Lake Today*](https://www.elliotlaketoday.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12747018), [*Flamborough Today*](https://www.flamboroughtoday.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12743859), [*Halton Hills Today*](https://www.haltonhillstoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12743932), [*Innisfil Today*](https://www.innisfiltoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12746381), [*Newmarket Today*](https://www.newmarkettoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12744527), [*Niagara on the Lake Local*](https://www.notllocal.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12744070), [*Orillia Matters*](https://www.orilliamatters.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-reporters-12745020), [*Pelham Today*](https://www.pelhamtoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12744168), [*Soo Today*](https://www.sootoday.com/local-news/thank-god-we-dont-have-the-media-ford-makes-another-announcement-without-inviting-reporters-12744738), [*Sudbury.com*](https://www.sudbury.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12743586), [*Thorold Today*](https://www.thoroldtoday.ca/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12744172), [*Timmins Today*](https://www.timminstoday.com/local-news/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12743554), [*Toronto Today*](https://www.torontotoday.ca/local/politics-government/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-with-no-reporters-12743268), [*Village Report*](https://www.villagereport.ca/village-picks/thank-god-we-dont-have-the-media-ford-holds-another-funding-announcement-without-inviting-reporters-12747603).

- [Is your MP still using X? After an investigation into non-consensual deepfakes, we analyzed the accounts](https://www.nationalobserver.com/2026/06/30/analysis/mps-on-x-analysis). *Canada's National Observer*, June 30, 2026.
- [‘Attacked no matter what they do’: why female politicians face relentless cycle of abuse](https://www.theguardian.com/world/2025/nov/12/female-politicians-such-as-mexicos-claudia-sheinbaum-face-backlash-driven-by-discrimination). *The Guardian*, November 12, 2025.
:::

#### Public scholarship

:::: {style="text-align: left"}
- **De Angelis, I.** (2025, April 16). Growing threats faced by women candidates undermine our democracy. *The Conversation*. <https://theconversation.com/growing-threats-faced-by-women-candidates-undermine-our-democracy-254371>
  - Republished in: [*The Hamilton Spectator*](https://www.thespec.com/opinion/contributors/growing-threats-faced-by-women-candidates-undermine-our-democracy/article_1fbe7ffa-78b9-53bb-b824-59db325ae1f8.html), [*St. Catherines Standard*](https://www.stcatharinesstandard.ca/opinion/contributors/growing-threats-faced-by-women-candidates-undermine-our-democracy/article_450e9927-0ba7-5874-b780-5f78e1e87b55.htm), [*The Peterborough Examiner*](https://www.thepeterboroughexaminer.com/opinion/contributors/growing-threats-faced-by-women-candidates-undermine-our-democracy/article_287d3d90-319a-5eff-b0a9-4f833830d3db.html), [*The Waterloo Region Record*](https://www.therecord.com/opinion/contributors/growing-threats-faced-by-women-candidates-undermine-our-democracy/article_669e7996-7f15-5cf9-8a44-75aa5dae4797.html), [*Welland Tribune*](https://www.wellandtribune.ca/opinion/contributors/growing-threats-faced-by-women-candidates-undermine-our-democracy/article_09f180c9-4dce-593b-aabc-ddf186d141fc.html), [*Niagara Falls Review*](https://www.niagarafallsreview.ca/opinion/contributors/growing-threats-faced-by-women-candidates-undermine-our-democracy/article_c58dc5ca-c2e3-5a2d-ba8f-f66efa36205d.html), [*Yahoo News (Canada)*](https://ca.news.yahoo.com/growing-threats-faced-women-candidates-203924922.html), [*MSN*](https://www.msn.com/en-ca/news/other/growing-threats-faced-by-women-candidates-undermine-our-democracy/ar-AA1D3IXI?ocid=bb7hp&apiversion=v2&noservercache=1&domshim=1&renderwebcomponents=1&wcseo=1&batchservertelemetry=1&noservertelemetry=1).

::::
